# Generated by Django 5.0.7 on 2024-09-25 16:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceInfo",
            fields=[
                (
                    "device_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "device_fqdn",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "device_platform_vendor",
                    models.CharField(
                        choices=[("f5", "f5"), ("haproxy", "haproxy")], max_length=10
                    ),
                ),
                ("cluster_primary_unit", models.CharField(max_length=50)),
                ("cluster_secondary_unit", models.CharField(default="", max_length=50)),
                ("cluster_tertiary_unit", models.CharField(default="", max_length=50)),
                (
                    "cluster_quaternary_unit",
                    models.CharField(default="", max_length=50),
                ),
                (
                    "device_datacenter",
                    models.CharField(
                        choices=[
                            ("ashburn", "ashburn"),
                            ("chicago", "chicago"),
                            ("hillsboro", "hillsboro"),
                        ],
                        default="ashburn",
                        max_length=10,
                    ),
                ),
                (
                    "device_security_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("internal", "internal"),
                            ("dmz", "dmz"),
                            ("none", "none"),
                        ],
                        default="none",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "object_db_status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("decommissioned", "decommissioned"),
                            ("designated", "designated"),
                        ],
                        default="active",
                    ),
                ),
                (
                    "device_role",
                    models.CharField(
                        choices=[
                            ("slb_shared", "SLB Shared"),
                            ("slb_private_gw", "SLB Private Gateway"),
                            ("GSLB", "GSLB"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("device_capabilities", models.CharField(default="", max_length=50)),
                (
                    "first_discovery_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
