# Generated by Django 5.1.5 on 2025-02-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_security_zone',
            field=models.CharField(blank=True, choices=[('internal', 'Green (Internal)'), ('dmz', 'Blue (DMZ / Internet or Partner Facing)'), ('sensitive', 'Black (Sensitive)'), ('office', 'Red (Office)'), ('none', 'none')], default='none', max_length=10, null=True),
        ),
    ]
