# Generated by Django 5.1.5 on 2025-02-05 03:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_inventory', '0002_alter_deviceinfo_device_security_zone'),
        ('slb_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('config_snapshot', models.JSONField(help_text='Configuration snapshot at deployment time')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_fqdn', models.ForeignKey(limit_choices_to={'device_platform_vendor': 'f5', 'object_db_status': 'active'}, on_delete=django.db.models.deletion.RESTRICT, related_name='deployments', to='device_inventory.deviceinfo')),
                ('frontend_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='slb_registry.frontendinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('detail', models.JSONField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='slb_registry.deploymenttransaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
